"""
Model 4: Steganographic Carrier
=================================
The visible Voynich text is a carrier generated by a simple mechanical
process. The actual message is encoded in the choices made among
equivalent options: which homophone variant was selected, whether a
word has prefix 'q' or 's', etc.

The carrier text is meaningless — it exists only to provide a space
in which covert choices can be embedded. The actual information is
in the deviations from the expected carrier pattern.

Historical plausibility: MODERATE
Predicted H2: N/A (carrier, not message)
Priority: MEDIUM

Critical test: Deviation stream entropy significantly lower than random bits.
"""

import random
import math
from collections import Counter, defaultdict
from typing import Dict, List, Tuple, Optional

from modules.phase2.base_model import Phase2GenerativeModel, VOYNICH_TARGETS
from data.voynich_corpus import get_all_tokens

class SteganographicCarrier(Phase2GenerativeModel):
    """
    Model 4: Steganographic Carrier.

    Builds a Markov model from the Voynich corpus and analyzes whether
    the actual text contains a hidden information channel encoded in
    the deviations from the expected carrier output.
    """

    MODEL_NAME = 'steganographic_carrier'
    MODEL_PRIORITY = 'MEDIUM'

    def __init__(self, carrier_order: int = 2,
                 choices_per_position: int = 3,
                 message_entropy: float = 1.5,
                 seed: int = 42, **kwargs):
        params = {
            'carrier_order': carrier_order,
            'choices_per_position': choices_per_position,
            'message_entropy': message_entropy,
            'seed': seed,
        }
        super().__init__(**params)

        self.carrier_order = carrier_order
        self.choices_per_position = choices_per_position
        self.message_entropy = message_entropy

        self.transition_model = {}
        self.vocabulary = []
        self._build_carrier_model()

    def _build_carrier_model(self):
        """Build a word-level Markov chain from the Voynich corpus."""
        tokens = get_all_tokens()
        if not tokens:
            return

        self.vocabulary = sorted(set(tokens))

        order = self.carrier_order
        for i in range(len(tokens) - order):
            context = tuple(tokens[i:i + order])
            next_word = tokens[i + order]
            if context not in self.transition_model:
                self.transition_model[context] = Counter()
            self.transition_model[context][next_word] += 1

    def generate(self, plaintext: str = '', n_words: int = 500) -> str:
        """
        Generate carrier text using the Markov model.

        If plaintext is provided, it's treated as the hidden message
        and encoded in the choice deviations among candidate words.
        Otherwise, generates pure carrier text.
        """
        if not self.transition_model:
            return ''

        contexts = list(self.transition_model.keys())
        context = list(self.rng.choice(contexts))
        output = list(context)

        message_bits = []
        if plaintext:
            for c in plaintext:
                bits = format(ord(c), '08b')
                message_bits.extend(int(b) for b in bits)

        bit_idx = 0

        for _ in range(n_words - len(context)):
            ctx = tuple(context[-self.carrier_order:])
            candidates = self.transition_model.get(ctx, {})

            if not candidates:
                word = self.rng.choice(self.vocabulary) if self.vocabulary else 'chedy'
            else:
                sorted_cands = sorted(candidates.items(), key=lambda x: -x[1])
                top_n = sorted_cands[:self.choices_per_position]

                if message_bits and bit_idx < len(message_bits):
                    n_choices = len(top_n)
                    if n_choices > 1:
                        choice_idx = message_bits[bit_idx] % n_choices
                        bit_idx += 1
                    else:
                        choice_idx = 0
                    word = top_n[choice_idx][0]
                else:
                    word = top_n[0][0]

            output.append(word)
            context.append(word)

        return ' '.join(output[:n_words])

    def _extract_deviations(self, text: str) -> List[float]:
        """
        Given a text, compute the deviation stream.

        For each word, compute the probability of choosing that specific
        word given the context. The deviation is how unlikely the choice
        was compared to the expected carrier output.

        Returns:
            List of surprisal values (-log2(p)) for each word.
        """
        tokens = text.split()
        if len(tokens) <= self.carrier_order:
            return []

        deviations = []
        for i in range(self.carrier_order, len(tokens)):
            ctx = tuple(tokens[i - self.carrier_order:i])
            word = tokens[i]
            candidates = self.transition_model.get(ctx, {})

            if not candidates:
                deviations.append(0.0)
                continue

            total = sum(candidates.values())
            word_count = candidates.get(word, 0)

            if word_count > 0:
                p = word_count / total
                surprisal = -math.log2(p)
            else:
                surprisal = -math.log2(1.0 / max(len(self.vocabulary), 1))

            deviations.append(surprisal)

        return deviations

    def _deviation_entropy(self, deviations: List[float]) -> float:
        """Compute the Shannon entropy of the deviation stream."""
        if not deviations:
            return 0.0

        n_bins = 10
        if max(deviations) == min(deviations):
            return 0.0

        bin_width = (max(deviations) - min(deviations)) / n_bins
        if bin_width == 0:
            return 0.0

        bin_counts = Counter()
        for d in deviations:
            bin_idx = min(int((d - min(deviations)) / bin_width), n_bins - 1)
            bin_counts[bin_idx] += 1

        total = len(deviations)
        entropy = -sum(
            (c / total) * math.log2(c / total)
            for c in bin_counts.values() if c > 0
        )
        return entropy

    def parameter_grid(self, resolution: str = 'medium') -> List[Dict]:
        """Generate parameter sweep grid."""
        if resolution == 'coarse':
            orders = [1, 2, 3]
            choices = [2, 3, 5]
            entropies = [1.0, 1.5]
        elif resolution == 'medium':
            orders = [1, 2, 3]
            choices = [2, 3, 4, 5]
            entropies = [0.5, 1.0, 1.5, 2.0]
        else:
            orders = [1, 2, 3, 4]
            choices = [2, 3, 4, 5, 6, 8]
            entropies = [0.5, 0.8, 1.0, 1.2, 1.5, 2.0, 2.5]

        grid = []
        for order in orders:
            for choices_n in choices:
                for ent in entropies:
                    grid.append({
                        'carrier_order': order,
                        'choices_per_position': choices_n,
                        'message_entropy': ent,
                        'seed': 42,
                    })
        return grid

    def critical_test(self, generated_profile: Dict) -> Dict:
        """
        Critical test: deviation stream must have structure.

        We test the ACTUAL Voynich corpus against the carrier model.
        If the deviation entropy is significantly lower than expected
        for random bits, there may be a hidden channel.
        """
        tokens = get_all_tokens()
        voynich_text = ' '.join(tokens) if tokens else ''

        if not voynich_text or not self.transition_model:
            return {
                'passes': False,
                'description': 'No corpus or model available',
                'details': {},
            }

        deviations = self._extract_deviations(voynich_text)
        if not deviations:
            return {
                'passes': False,
                'description': 'No deviations extracted',
                'details': {},
            }

        dev_entropy = self._deviation_entropy(deviations)

        max_entropy = math.log2(10)
        ratio = dev_entropy / max_entropy if max_entropy > 0 else 1.0

        passes = ratio < 0.7

        mean_dev = sum(deviations) / len(deviations) if deviations else 0
        std_dev = (sum((d - mean_dev)**2 for d in deviations) / len(deviations))**0.5 if deviations else 0

        return {
            'passes': passes,
            'description': (
                f'Deviation entropy = {dev_entropy:.4f} '
                f'({ratio:.1%} of maximum {max_entropy:.4f}). '
                f'{"PASS: structure detected" if passes else "FAIL: near-random deviations"}'
            ),
            'details': {
                'deviation_entropy': dev_entropy,
                'max_entropy': max_entropy,
                'entropy_ratio': ratio,
                'threshold': 0.7,
                'mean_surprisal': mean_dev,
                'std_surprisal': std_dev,
                'n_deviations': len(deviations),
                'structure_detected': passes,
            },
        }
